#!/bin/sh

case "${1}" in
	hibernate|suspend)
		# Unbind ehci for preventing error
		echo -n "0000:00:1d.0" | tee /sys/bus/pci/drivers/ehci-pci/unbind
		# Unbind snd_hda_intel for sound
		echo -n "0000:00:1b.0" | tee /sys/bus/pci/drivers/snd_hda_intel/unbind
		echo -n "0000:00:03.0" | tee /sys/bus/pci/drivers/snd_hda_intel/unbind
	;;
	resume|thaw)
		# Unbind ehci for preventing error
		echo -n "0000:00:1d.0" | tee /sys/bus/pci/drivers/ehci-pci/unbind
		# Bind snd_hda_intel for sound
		echo -n "0000:00:1b.0" | tee /sys/bus/pci/drivers/snd_hda_intel/bind
		echo -n "0000:00:03.0" | tee /sys/bus/pci/drivers/snd_hda_intel/bind
		
		# Shutdown pulseaudio so that we can restart alsa. It will
		# automatically start again. Then let alsa know that we have
		# re-enabled these devices
		killall pulseaudio && alsa force-reload
	;;

esac
